"""Materialize the governed dbt / Dagster projects into any workspace (#325).

``seshat dbt`` needs ``<root>/dbt/`` (project, macros, selectors), the root
``profiles.example.yml``, and the run-evidence schema; ``seshat dagster``
needs ``<root>/orchestration/dagster/``. Those artifacts previously shipped
only with the development repository, so a bare ``pip install seshat-bi[dbt]``
left both capabilities dead -- violating the portable operating contract's
"Never require the Seshat development repository for normal use".

``seshat dbt init`` / ``seshat dagster init`` close that gap by materializing
the GENERIC governed artifacts from bundled package data (wheel force-include;
a development checkout falls back to the repo files, mirroring
``seshat.demo.fixtures``). Constitution VII holds: only table-neutral files
are bundled -- ``selectors.yml`` is GENERATED table-neutral here, never copied,
because the committed dev-repo copy carries the worked example's selector.
Both inits are write-only and per-file non-destructive: an existing file is
always kept, never overwritten.
"""

from __future__ import annotations

from collections.abc import Iterator
from dataclasses import dataclass
from importlib.resources import files
from pathlib import Path

_SOURCE_ROOT = Path(__file__).resolve().parents[2]
_PACKAGED_ROOT = "governed_projects"

# The bundle-safe generic dbt working set (everything else under the dev
# repo's dbt/models/** is worked-example content and MUST NOT ship).
_DBT_FILES = (
    "dbt/dbt_project.yml",
    "dbt/macros/generate_schema_name.sql",
    "profiles.example.yml",
    "schemas/dbt-run-evidence.schema.json",
)

# The table-neutral Dagster orchestration project (its tests/ stay dev-only).
_DAGSTER_FILES = (
    "orchestration/dagster/pyproject.toml",
    "orchestration/dagster/.gitignore",
    "orchestration/dagster/README.md",
    "orchestration/dagster/run-evidence/README.md",
    "schemas/dagster-run-evidence.schema.json",
)
_DAGSTER_SRC_DIR = "orchestration/dagster/src"

# `seshat dbt doctor` requires these exact local-output ignore rules.
_REQUIRED_IGNORES = (
    "/profiles.yml",
    "/.user.yml",
    "/dbt/target/",
    "/dbt/logs/",
    "/.seshat/dbt/",
)

# Generated, never bundled: table-neutral bootstrap selector (dbt refuses an
# empty selectors list, and the dev repo's committed selectors.yml names the
# worked example's table). Replace with per-table seshat_table_<table_id>
# selectors as tables are onboarded.
_SELECTORS_BOOTSTRAP = """\
# Generated by `seshat dbt init`. Governed selection is tag-driven: add ONE
# selector per governed table, named seshat_table_<table_id>, with
# {method: tag, value: seshat_table_<table_id>}. The bootstrap entry below
# only keeps this file valid before the first table is onboarded.
selectors:
  - name: seshat_workspace_bootstrap
    description: >-
      Placeholder selector created by `seshat dbt init`; selects nothing
      until models carry its tag. Add seshat_table_<table_id> selectors
      per governed table.
    definition:
      method: tag
      value: seshat_workspace_bootstrap
"""

_DAGSTER_NEXT_STEPS = (
    "next: create the orchestration environment -- cd orchestration/dagster "
    '&& uv venv .venv && uv pip install -p .venv -e "../..[dbt]" -e ".[dev]" '
    "-- then `seshat dagster doctor`"
)


@dataclass(frozen=True)
class InitReport:
    """What one governed-project init did, per file, plus operator next steps."""

    written: tuple[str, ...]
    kept: tuple[str, ...]
    notes: tuple[str, ...]


def _packaged(relative: str):
    return files("seshat").joinpath(_PACKAGED_ROOT, *relative.split("/"))


def _resource_bytes(relative: str) -> bytes:
    """One bundled template's bytes: wheel data first, dev checkout fallback."""
    packaged = _packaged(relative)
    if packaged.is_file():
        return packaged.read_bytes()
    source = _SOURCE_ROOT / relative
    if source.is_file():
        return source.read_bytes()
    raise FileNotFoundError(
        f"bundled governed template is missing: {relative} "
        "(reinstall seshat-bi, or run from a development checkout)"
    )


def _walk_packaged(node, prefix: str) -> Iterator[str]:
    for child in node.iterdir():
        if child.name == "__pycache__":
            continue
        if child.is_dir():
            yield from _walk_packaged(child, f"{prefix}/{child.name}")
        else:
            yield f"{prefix}/{child.name}"


def _tree_files(relative_dir: str) -> tuple[str, ...]:
    """Every bundled file under a template directory, wheel-data first."""
    packaged = _packaged(relative_dir)
    if packaged.is_dir():
        return tuple(sorted(_walk_packaged(packaged, relative_dir)))
    source = _SOURCE_ROOT / relative_dir
    if source.is_dir():
        return tuple(
            sorted(
                (Path(relative_dir) / path.relative_to(source)).as_posix()
                for path in source.rglob("*")
                if path.is_file() and "__pycache__" not in path.parts
            )
        )
    raise FileNotFoundError(
        f"bundled governed project tree is missing: {relative_dir} "
        "(reinstall seshat-bi, or run from a development checkout)"
    )


def _write_if_absent(root: Path, relative: str, data: bytes) -> bool:
    """Write one template file; True when written, False when kept as-is."""
    target = root / Path(*relative.split("/"))
    if target.exists():
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(data)
    return True


def _ensure_ignore_rules(root: Path, notes: list[str]) -> None:
    """Append (never rewrite) the ignore rules `seshat dbt doctor` requires."""
    gitignore = root / ".gitignore"
    existing = (
        gitignore.read_text(encoding="utf-8").splitlines()
        if gitignore.is_file()
        else []
    )
    missing = [line for line in _REQUIRED_IGNORES if line not in existing]
    if not missing:
        return
    lines = [*existing, "# seshat dbt local outputs (added by `seshat dbt init`)"]
    lines.extend(missing)
    gitignore.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    notes.append(f".gitignore: appended {len(missing)} dbt local-output rules")


def dbt_init(repo_root: Path) -> InitReport:
    """Materialize the generic governed dbt working set into a workspace."""

    root = Path(repo_root).resolve()
    written: list[str] = []
    kept: list[str] = []
    notes: list[str] = []
    generated = {
        "dbt/selectors.yml": _SELECTORS_BOOTSTRAP.encode("utf-8"),
        "dbt/models/.gitkeep": b"",
    }
    materialized = {
        **{relative: _resource_bytes(relative) for relative in _DBT_FILES},
        **generated,
    }
    for relative, data in materialized.items():
        (written if _write_if_absent(root, relative, data) else kept).append(relative)
    _ensure_ignore_rules(root, notes)
    notes.append(
        "next: copy profiles.example.yml to the gitignored profiles.yml, set "
        "the SESHAT_DBT_* keys in .env, then `seshat dbt doctor`"
    )
    return InitReport(written=tuple(written), kept=tuple(kept), notes=tuple(notes))


def dagster_init(repo_root: Path) -> InitReport:
    """Materialize the governed Dagster orchestration project into a workspace."""

    root = Path(repo_root).resolve()
    written: list[str] = []
    kept: list[str] = []
    for relative in (*_DAGSTER_FILES, *_tree_files(_DAGSTER_SRC_DIR)):
        data = _resource_bytes(relative)
        (written if _write_if_absent(root, relative, data) else kept).append(relative)
    return InitReport(
        written=tuple(written),
        kept=tuple(kept),
        notes=(_DAGSTER_NEXT_STEPS,),
    )
