table Sales
	measure Revenue = SUM(Sales[Amount])
		displayFolder: KPIs

	partition Sales = m
		source =
			let
				Src = PostgreSQL.Database(ServerParam, DbParam),
				Data = Value.NativeQuery(Src, "SELECT * FROM gold.fct_sales")
			in
				Data
