"""Compass projection generator + drift checks (feature 070).

ONE canonical source (``.seshat/kit-source.yaml``) is PROJECTED into:
  - ``.seshat/compass.yaml``            the harness-neutral kit router;
  - the fenced ``SESHAT-KIT`` prose     (written into AGENTS.md / CLAUDE.md by fence);
  - ``.seshat/manifest.yaml`` + ``.seshat/integrations/*.json``  integrity receipts.

Two DISTINCT drift checks (contracts/{compass-yaml,fence}.contract.md):
  (a) ``check_yaml_drift``  -- ``compass.yaml == project_yaml(source)`` byte-exact (P1);
  (b) ``check_prose_drift`` -- ``fenced_body == render_prose(source)`` render-compare
      (FC1, MINOR-6) -- prose cannot be byte-compared to YAML.

This module does NO DB, NO network, NO execution. It MAY import ``pyyaml`` (already in
the ``dev`` extra) -- like ``semantic-check`` / ``value-check``, and unlike the
stdlib-only ``retail check`` core, to which this feature adds no rule. Authored files
are UTF-8 without BOM, ``\\n`` endings, ASCII-safe (Principle IX).
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import yaml

SOURCE_REL = ".seshat/kit-source.yaml"
COMPASS_REL = ".seshat/compass.yaml"
MANIFEST_REL = ".seshat/manifest.yaml"
INTEGRATIONS_DIR_REL = ".seshat/integrations"

# The keys copied verbatim from source into the compass router. `current_stage`
# is deliberately NOT here (FR-005: no run-state).
_COMPASS_KEYS = ("kit", "version", "orient", "verbs", "hard_stops", "integrations")


def load_source(repo: Path | str) -> dict:
    """Parse the canonical ``kit-source.yaml`` (lazy-ish yaml import at module top)."""
    repo = Path(repo)
    text = (repo / SOURCE_REL).read_text(encoding="utf-8-sig")
    data = yaml.safe_load(text)
    if not isinstance(data, dict):
        raise ValueError(f"{SOURCE_REL} must be a YAML mapping")
    return data


def render_compass_yaml(source: dict) -> str:
    """Render ``compass.yaml`` deterministically from ``source`` (the projection).

    Copies the declarative blocks verbatim; never emits ``current_stage``. The
    output is the single canonical serialization used both to WRITE the file and to
    RE-RENDER for the byte-exact drift check, so the two cannot disagree.
    """
    projected = {k: source[k] for k in _COMPASS_KEYS if k in source}
    header = (
        "# GENERATED by retail init (compass projection of .seshat/kit-source.yaml).\n"
        "# Do not edit by hand -- edit kit-source.yaml and re-run `retail init`.\n"
        "# Harness-neutral kit router. Stores NO run-state / current_stage (FR-005).\n"
    )
    body = yaml.safe_dump(
        projected,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=False,
        width=1000,
    )
    return header + body


def render_prose(source: dict) -> str:
    """Render the fenced ``SESHAT-KIT`` prose projection from ``source``.

    A DIFFERENT shape from the YAML (Markdown prose), so it is compared by
    render-and-compare (FC1), never byte-vs-YAML.
    """
    lines: list[str] = []
    lines.append(
        f"**Seshat BI kit router** (v{source.get('version', '?')}) -- "
        "generated from `.seshat/kit-source.yaml`; do not edit here."
    )
    lines.append("")
    orient = source.get("orient", {})
    lines.append(
        f"Orient first: *{orient.get('question_first', '')}* "
        f"State lives in `{orient.get('state_lives_in', '')}` "
        "(recomputed; this file stores none)."
    )
    lines.append("")
    lines.append("Verbs the agent drives:")
    for v in source.get("verbs", []):
        lines.append(f"- `{v['id']}` -- {v['purpose']}")
    lines.append("")
    lines.append(
        "Hard-stops (orientation the agent reads; enforcement is the lint "
        "rules + G6/C2, not this file):"
    )
    for h in source.get("hard_stops", []):
        lines.append(f"- {h}")
    return "\n".join(lines)


def check_yaml_drift(repo: Path | str) -> bool:
    """(a) True iff on-disk ``compass.yaml`` byte-equals ``project_yaml(source)``."""
    repo = Path(repo)
    expected = render_compass_yaml(load_source(repo))
    try:
        actual = (repo / COMPASS_REL).read_text(encoding="utf-8-sig")
    except OSError:
        return False
    return actual == expected


def check_prose_drift(source: dict, fenced_body: str) -> bool:
    """(b) True iff ``fenced_body`` equals the canonical prose render of ``source``."""
    return fenced_body == render_prose(source)


def _manifest(repo: Path, files: list[str]) -> str:
    entries = []
    for rel in files:
        raw = (repo / rel).read_bytes()
        entries.append({"path": rel, "checksum": hashlib.sha256(raw).hexdigest()})
    doc = {"kit": "seshat-bi", "files": entries}
    return yaml.safe_dump(doc, sort_keys=False, allow_unicode=False, width=1000)


def project_all(repo: Path | str) -> tuple[str, ...]:
    """Write compass.yaml + manifests from the canonical source. Returns written paths.

    Does NOT write the fenced AGENTS.md/CLAUDE.md regions -- that is fence.write_fence,
    called by kit_init with ``render_prose(source)`` -- so this module never edits a
    governed file.
    """
    repo = Path(repo)
    source = load_source(repo)

    written: list[str] = []
    _write(repo / COMPASS_REL, render_compass_yaml(source))
    written.append(COMPASS_REL)

    # Per-harness integration manifests (speckit's integrity-receipt part).
    for harness in source.get("integrations", []):
        rel = f"{INTEGRATIONS_DIR_REL}/{harness}.json"
        payload = {
            "harness": harness,
            "files": [COMPASS_REL],
            "checksum": hashlib.sha256((repo / COMPASS_REL).read_bytes()).hexdigest(),
        }
        _write(repo / rel, json.dumps(payload, indent=2, sort_keys=True) + "\n")
        written.append(rel)

    # Kit file inventory + checksums (covers the source + compass + integrations).
    inventory = [SOURCE_REL, COMPASS_REL] + [
        f"{INTEGRATIONS_DIR_REL}/{h}.json" for h in source.get("integrations", [])
    ]
    _write(repo / MANIFEST_REL, _manifest(repo, inventory))
    written.append(MANIFEST_REL)

    return tuple(written)


def _write(path: Path, text: str) -> None:
    """Write UTF-8 without BOM and ``\\n`` line endings (Windows-stable)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
