"""Rule package.

Importing this package imports every rule submodule so that each module's
``@register(...)`` decorators fire exactly once. The runner does
``import seshat.rules`` at startup before calling ``registry.all_rules()``.

Add a new submodule to the import list below when you add a new rule group;
that is the *only* wiring step required for new rules to be discovered.
"""

from __future__ import annotations

# Side-effecting imports: each module registers its rules on import.
from . import (  # noqa: F401  (imported for side effects)
    additivity_consistency,
    answerability_reconciler,
    assumption_coherence,
    assumptions,
    comparison_baseline,
    conformed_dimension,
    currency_unit,
    date_spine,
    dax,
    design_background,
    design_categorical_distinctness,
    design_contrast,
    design_grid_closure,
    design_ramp_deltae,
    design_review_evidence,
    design_routes,
    design_theme,
    design_theme_fidelity,
    design_visual_selfcheck,
    formatting_plan,
    g6,
    git_meta,
    live_surface_boundary,
    never_execute,
    parked_on,
    pbir,
    publish_pack,
    readiness_status,
    reload_idempotency,
    rename_impact_guard,
    rls_access,
    routes,
    routes_coverage,
    rule_ap1,
    rule_count_claims,
    rule_sf1,
    scorecard,
    snapshot_time_additivity,
    source_data_contract,
    source_freshness,
    sql,
    status_claims,
)

__all__ = [
    "additivity_consistency",
    "answerability_reconciler",
    "assumption_coherence",
    "assumptions",
    "comparison_baseline",
    "conformed_dimension",
    "currency_unit",
    "date_spine",
    "dax",
    "design_background",
    "design_categorical_distinctness",
    "design_contrast",
    "design_grid_closure",
    "design_ramp_deltae",
    "design_review_evidence",
    "design_routes",
    "design_theme",
    "design_theme_fidelity",
    "design_visual_selfcheck",
    "formatting_plan",
    "g6",
    "git_meta",
    "live_surface_boundary",
    "never_execute",
    "parked_on",
    "pbir",
    "publish_pack",
    "readiness_status",
    "reload_idempotency",
    "rename_impact_guard",
    "rls_access",
    "routes",
    "routes_coverage",
    "rule_ap1",
    "rule_count_claims",
    "rule_sf1",
    "scorecard",
    "snapshot_time_additivity",
    "source_data_contract",
    "source_freshness",
    "sql",
    "status_claims",
]
