-- 0002_create_gold_star.sql
-- Build the gold Kimball star schema over silver.sales_c086.
--
-- Power BI reads gold. One fact (line-item grain) + 6 conformed dimensions.
-- Surrogate _sk keys (GENERATED ... IDENTITY), natural keys retained, an unknown
-- member (_sk = -1) in every dim, fact FKs COALESCE missing/unknown lookups to -1.
-- invoice_no + line_no are DEGENERATE dimensions: they live on the fact, not a dim.
--
-- Idempotent: drop fact before dims (FK order), recreate all in one transaction.
-- Save UTF-8 without BOM (English labels only here; silver already de-Arabic'd
-- billing_type, but set client_encoding defensively).

SET client_encoding TO 'UTF8';

BEGIN;

CREATE SCHEMA IF NOT EXISTS gold;

-- FK dependency order: fact first.
DROP TABLE IF EXISTS gold.fct_sales;
DROP TABLE IF EXISTS gold.dim_product;
DROP TABLE IF EXISTS gold.dim_customer;
DROP TABLE IF EXISTS gold.dim_salesperson;
DROP TABLE IF EXISTS gold.dim_date;
DROP TABLE IF EXISTS gold.dim_billing_type;
DROP TABLE IF EXISTS gold.dim_branch;

-- ============================================================ dim_product
CREATE TABLE gold.dim_product (
  product_sk          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id          TEXT,                 -- natural key
  product_name        TEXT,
  product_brand       TEXT,
  product_group       TEXT,
  product_cluster     TEXT,
  product_division    TEXT,
  product_category    TEXT,
  product_subcategory TEXT,
  product_segment     TEXT,
  business_segment    TEXT
);
INSERT INTO gold.dim_product OVERRIDING SYSTEM VALUE
  VALUES (-1,'UNKNOWN','Unknown','Unknown','Unknown','Unknown','Unknown','Unknown','Unknown','Unknown','UNMAPPED');
INSERT INTO gold.dim_product
  (product_id, product_name, product_brand, product_group, product_cluster,
   product_division, product_category, product_subcategory, product_segment, business_segment)
SELECT product_id, max(product_name), max(product_brand), max(product_group), max(product_cluster),
       max(product_division), max(product_category), max(product_subcategory), max(product_segment), max(business_segment)
FROM silver.sales_c086
GROUP BY product_id;  -- product_id->attributes verified 1:1; max() is a safe collapse

-- ============================================================ dim_customer
CREATE TABLE gold.dim_customer (
  customer_sk   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   TEXT,
  customer_name TEXT
);
INSERT INTO gold.dim_customer OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown');
INSERT INTO gold.dim_customer (customer_id, customer_name)
SELECT customer_id, max(customer_name) FROM silver.sales_c086 GROUP BY customer_id;

-- ============================================================ dim_salesperson
CREATE TABLE gold.dim_salesperson (
  salesperson_sk   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  salesperson_id   TEXT,
  salesperson_name TEXT,
  job_title        TEXT
);
INSERT INTO gold.dim_salesperson OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown','Unknown');
-- silver already filled missing salesperson_id with 'UNKNOWN'; fold that into the -1 member
INSERT INTO gold.dim_salesperson (salesperson_id, salesperson_name, job_title)
SELECT salesperson_id, max(salesperson_name), max(job_title)
FROM silver.sales_c086
WHERE salesperson_id <> 'UNKNOWN'
GROUP BY salesperson_id;

-- ============================================================ dim_billing_type
CREATE TABLE gold.dim_billing_type (
  billing_type_sk    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billing_type_code  TEXT,
  billing_type       TEXT,
  is_return          BOOLEAN
);
INSERT INTO gold.dim_billing_type OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown',FALSE);
INSERT INTO gold.dim_billing_type (billing_type_code, billing_type, is_return)
SELECT billing_type_code, max(billing_type), bool_or(is_return)
FROM silver.sales_c086 GROUP BY billing_type_code;

-- ============================================================ dim_branch
CREATE TABLE gold.dim_branch (
  branch_sk   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_code TEXT,
  branch_name TEXT
);
INSERT INTO gold.dim_branch OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown');
INSERT INTO gold.dim_branch (branch_code, branch_name)
SELECT branch_code, max(branch_name) FROM silver.sales_c086 GROUP BY branch_code;

-- ============================================================ dim_date (contiguous)
CREATE TABLE gold.dim_date (
  date_sk    INT PRIMARY KEY,             -- smart key YYYYMMDD
  full_date  DATE,
  year       SMALLINT,
  quarter    SMALLINT,
  month      SMALLINT,
  month_name TEXT,
  day        SMALLINT,
  day_name   TEXT,
  iso_week   SMALLINT,
  is_weekend BOOLEAN
);
-- -1 unknown member
INSERT INTO gold.dim_date VALUES (-1, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Unknown', NULL, NULL);
-- generate a CONTIGUOUS calendar over the full span (covers the 2 zero-sales gap days)
INSERT INTO gold.dim_date
SELECT
  (to_char(d,'YYYYMMDD'))::int      AS date_sk,
  d::date                            AS full_date,
  extract(year FROM d)::smallint,
  extract(quarter FROM d)::smallint,
  extract(month FROM d)::smallint,
  to_char(d,'Month'),
  extract(day FROM d)::smallint,
  to_char(d,'Day'),
  extract(week FROM d)::smallint,
  (extract(isodow FROM d) >= 6)      AS is_weekend
FROM generate_series(DATE '2023-01-01', DATE '2025-12-31', INTERVAL '1 day') AS g(d);

-- ============================================================ fct_sales
CREATE TABLE gold.fct_sales (
  fct_sales_sk        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- degenerate dimensions (live on the fact)
  invoice_no          TEXT NOT NULL,
  line_no             SMALLINT NOT NULL,
  original_invoice_ref TEXT,
  -- foreign keys to dims
  product_sk          INT NOT NULL,
  customer_sk         INT NOT NULL,
  salesperson_sk      INT NOT NULL,
  date_sk             INT NOT NULL,
  billing_type_sk     INT NOT NULL,
  branch_sk           INT NOT NULL,
  -- measures
  quantity            NUMERIC(18,4),
  sales_amount        NUMERIC(18,2),
  net_amount          NUMERIC(18,2),
  tax_amount          NUMERIC(18,2),
  discount_amount     NUMERIC(18,2),
  is_return           BOOLEAN
);
INSERT INTO gold.fct_sales
  (invoice_no, line_no, original_invoice_ref,
   product_sk, customer_sk, salesperson_sk, date_sk, billing_type_sk, branch_sk,
   quantity, sales_amount, net_amount, tax_amount, discount_amount, is_return)
SELECT
  s.invoice_no, s.line_no, s.original_invoice_ref,
  COALESCE(dp.product_sk, -1),
  COALESCE(dc.customer_sk, -1),
  COALESCE(dsp.salesperson_sk, -1),
  COALESCE(dd.date_sk, -1),
  COALESCE(dbt.billing_type_sk, -1),
  COALESCE(db.branch_sk, -1),
  s.quantity, s.sales_amount, s.net_amount, s.tax_amount, s.discount_amount, s.is_return
FROM silver.sales_c086 s
LEFT JOIN gold.dim_product      dp  ON dp.product_id   = s.product_id
LEFT JOIN gold.dim_customer     dc  ON dc.customer_id  = s.customer_id
LEFT JOIN gold.dim_salesperson  dsp ON dsp.salesperson_id = s.salesperson_id
LEFT JOIN gold.dim_date         dd  ON dd.full_date    = s.sale_date
LEFT JOIN gold.dim_billing_type dbt ON dbt.billing_type_code = s.billing_type_code
LEFT JOIN gold.dim_branch       db  ON db.branch_code  = s.branch_code;

-- FK constraints (after load, so the -1 members and rows exist)
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_product      FOREIGN KEY (product_sk)      REFERENCES gold.dim_product (product_sk);
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_customer     FOREIGN KEY (customer_sk)     REFERENCES gold.dim_customer (customer_sk);
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_salesperson  FOREIGN KEY (salesperson_sk)  REFERENCES gold.dim_salesperson (salesperson_sk);
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_date         FOREIGN KEY (date_sk)         REFERENCES gold.dim_date (date_sk);
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_billing_type FOREIGN KEY (billing_type_sk) REFERENCES gold.dim_billing_type (billing_type_sk);
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_branch       FOREIGN KEY (branch_sk)       REFERENCES gold.dim_branch (branch_sk);

-- indexes on FKs for star-join performance
CREATE INDEX idx_fct_product_sk      ON gold.fct_sales (product_sk);
CREATE INDEX idx_fct_customer_sk     ON gold.fct_sales (customer_sk);
CREATE INDEX idx_fct_salesperson_sk  ON gold.fct_sales (salesperson_sk);
CREATE INDEX idx_fct_date_sk         ON gold.fct_sales (date_sk);
CREATE INDEX idx_fct_billing_type_sk ON gold.fct_sales (billing_type_sk);

COMMIT;
