-- 0004_create_gold_retail_store_sales_star.sql
-- Build the gold Kimball star over silver.retail_store_sales.
--
-- Power BI reads gold. One fact (transaction grain) + 4 conformed dims + dim_date.
-- Surrogate _sk keys (GENERATED ... IDENTITY), natural keys retained, an unknown
-- member (_sk = -1) in every ENTITY dim (fact FKs COALESCE missing lookups to -1);
-- the DATE dim carries NO -1 member (marked date table, rule S8) -- an unmatched
-- fact date is rejected by date_sk NOT NULL, not absorbed by a sentinel.
-- transaction_id + discount_applied are DEGENERATE dims: they live on the fact.
--
-- Idempotent: drop fact before dims (FK order), recreate all in one transaction.
-- ASCII only (English labels); UTF-8 no BOM. dim_date span 2022-01-01..2025-01-18
-- (from the approved source-map.yaml; covers every transaction_date contiguously).

SET client_encoding TO 'UTF8';

BEGIN;

CREATE SCHEMA IF NOT EXISTS gold;

-- FK dependency order: fact first.
DROP TABLE IF EXISTS gold.fct_sales_rss;
DROP TABLE IF EXISTS gold.dim_customer_rss;
DROP TABLE IF EXISTS gold.dim_product_rss;
DROP TABLE IF EXISTS gold.dim_payment_method_rss;
DROP TABLE IF EXISTS gold.dim_location_rss;
DROP TABLE IF EXISTS gold.dim_date_rss;

-- ============================================================ dim_customer_rss
CREATE TABLE gold.dim_customer_rss (
  customer_sk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id TEXT                       -- pseudonymous natural key (Q1: kept)
);
INSERT INTO gold.dim_customer_rss OVERRIDING SYSTEM VALUE VALUES (-1, 'UNKNOWN');
INSERT INTO gold.dim_customer_rss (customer_id)
SELECT customer_id FROM silver.retail_store_sales
WHERE customer_id IS NOT NULL
GROUP BY customer_id;

-- ============================================================ dim_product_rss
-- item is the product natural key; category is its 1:1 attribute (0 fan-out verified).
CREATE TABLE gold.dim_product_rss (
  product_sk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item       TEXT,                       -- natural key
  category   TEXT
);
INSERT INTO gold.dim_product_rss OVERRIDING SYSTEM VALUE VALUES (-1, 'UNKNOWN', 'Unknown');
-- the 9.65% NULL item collapses to the -1 unknown member via the fact COALESCE (Q4)
INSERT INTO gold.dim_product_rss (item, category)
SELECT item, max(category)              -- item->category verified 1:1; max() is a safe collapse
FROM silver.retail_store_sales
WHERE item IS NOT NULL
GROUP BY item;

-- ============================================================ dim_payment_method_rss
CREATE TABLE gold.dim_payment_method_rss (
  payment_method_sk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_method    TEXT
);
INSERT INTO gold.dim_payment_method_rss OVERRIDING SYSTEM VALUE VALUES (-1, 'UNKNOWN');
INSERT INTO gold.dim_payment_method_rss (payment_method)
SELECT payment_method FROM silver.retail_store_sales
WHERE payment_method IS NOT NULL
GROUP BY payment_method;

-- ============================================================ dim_location_rss
CREATE TABLE gold.dim_location_rss (
  location_sk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location    TEXT
);
INSERT INTO gold.dim_location_rss OVERRIDING SYSTEM VALUE VALUES (-1, 'UNKNOWN');
INSERT INTO gold.dim_location_rss (location)
SELECT location FROM silver.retail_store_sales
WHERE location IS NOT NULL
GROUP BY location;

-- ============================================================ dim_date_rss (contiguous)
CREATE TABLE gold.dim_date_rss (
  date_sk    INT PRIMARY KEY,            -- smart key YYYYMMDD
  full_date  DATE,
  year       SMALLINT,
  quarter    SMALLINT,
  month      SMALLINT,
  month_name TEXT,
  day        SMALLINT,
  day_name   TEXT,
  iso_week   SMALLINT,
  is_weekend BOOLEAN
);
-- NO -1 unknown member: dim_date_rss is a MARKED date table (dataCategory: Time),
-- which Power BI validates as unique/contiguous/NO-nulls. A -1,NULL member would
-- break that (Codex review #1 / rule S8). An unmatched fact date is handled by
-- date_sk NOT NULL below (the load fails loudly), never by a sentinel member.
-- CONTIGUOUS calendar over the full span (RC15; never SELECT DISTINCT date)
INSERT INTO gold.dim_date_rss
SELECT
  (to_char(d,'YYYYMMDD'))::int       AS date_sk,
  d::date                             AS full_date,
  extract(year FROM d)::smallint,
  extract(quarter FROM d)::smallint,
  extract(month FROM d)::smallint,
  to_char(d,'Month'),
  extract(day FROM d)::smallint,
  to_char(d,'Day'),
  extract(week FROM d)::smallint,
  (extract(isodow FROM d) >= 6)       AS is_weekend
FROM generate_series(DATE '2022-01-01', DATE '2025-01-18', INTERVAL '1 day') AS g(d);

-- ============================================================ fct_sales_rss
CREATE TABLE gold.fct_sales_rss (
  fct_sales_rss_sk  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- degenerate dimensions (live on the fact)
  transaction_id    TEXT NOT NULL,
  discount_applied  BOOLEAN,             -- discount flag; NULL = unknown (Q2)
  -- foreign keys to dims
  customer_sk       INT NOT NULL,
  product_sk        INT NOT NULL,
  payment_method_sk INT NOT NULL,
  location_sk       INT NOT NULL,
  date_sk           INT NOT NULL,
  -- measures
  price_per_unit    NUMERIC(12,2),
  quantity          NUMERIC(12,2),
  total_spent       NUMERIC(12,2)
);
INSERT INTO gold.fct_sales_rss
  (transaction_id, discount_applied,
   customer_sk, product_sk, payment_method_sk, location_sk, date_sk,
   price_per_unit, quantity, total_spent)
SELECT
  s.transaction_id, s.discount_applied,
  COALESCE(dc.customer_sk, -1),
  COALESCE(dp.product_sk, -1),
  COALESCE(dpm.payment_method_sk, -1),
  COALESCE(dl.location_sk, -1),
  dd.date_sk,   -- NO COALESCE to a -1 date member: an unmatched/NULL fact date
                -- yields NULL and is rejected by date_sk NOT NULL (fail loud,
                -- a real calendar-coverage bug), never silently bucketed (Codex #2)
  s.price_per_unit, s.quantity, s.total_spent
FROM silver.retail_store_sales s
LEFT JOIN gold.dim_customer_rss       dc  ON dc.customer_id     = s.customer_id
LEFT JOIN gold.dim_product_rss        dp  ON dp.item            = s.item
LEFT JOIN gold.dim_payment_method_rss dpm ON dpm.payment_method = s.payment_method
LEFT JOIN gold.dim_location_rss       dl  ON dl.location        = s.location
LEFT JOIN gold.dim_date_rss           dd  ON dd.full_date       = s.transaction_date;

-- FK constraints (after load, so the -1 members and rows exist)
ALTER TABLE gold.fct_sales_rss ADD CONSTRAINT fk_fct_rss_customer       FOREIGN KEY (customer_sk)       REFERENCES gold.dim_customer_rss (customer_sk);
ALTER TABLE gold.fct_sales_rss ADD CONSTRAINT fk_fct_rss_product        FOREIGN KEY (product_sk)        REFERENCES gold.dim_product_rss (product_sk);
ALTER TABLE gold.fct_sales_rss ADD CONSTRAINT fk_fct_rss_payment_method FOREIGN KEY (payment_method_sk) REFERENCES gold.dim_payment_method_rss (payment_method_sk);
ALTER TABLE gold.fct_sales_rss ADD CONSTRAINT fk_fct_rss_location       FOREIGN KEY (location_sk)       REFERENCES gold.dim_location_rss (location_sk);
ALTER TABLE gold.fct_sales_rss ADD CONSTRAINT fk_fct_rss_date           FOREIGN KEY (date_sk)           REFERENCES gold.dim_date_rss (date_sk);

-- indexes on FKs for star-join performance
CREATE INDEX idx_fct_rss_customer_sk       ON gold.fct_sales_rss (customer_sk);
CREATE INDEX idx_fct_rss_product_sk        ON gold.fct_sales_rss (product_sk);
CREATE INDEX idx_fct_rss_payment_method_sk ON gold.fct_sales_rss (payment_method_sk);
CREATE INDEX idx_fct_rss_location_sk       ON gold.fct_sales_rss (location_sk);
CREATE INDEX idx_fct_rss_date_sk           ON gold.fct_sales_rss (date_sk);

COMMIT;
