-- 0006_create_gold_sales_c086_star.sql
-- Build the gold Kimball star over silver.sales_c086 (the 0005 build).
--
-- SUPERSEDES 0002_create_gold_star.sql. Authoritative gold build for the FINAL map.
-- Differs from 0002 by design:
--   * fct_sales PK = sale_sk (carried from silver); natural key is degenerate-on-fact.
--   * 2 measures only: gross_sales + quantity (net/tax/discount dropped).
--   * NEW dim_product_purchaser (the counter agent, 16 members).
--   * dim_customer keyed on customer_id_clean (the 'WALK_IN' remap), not raw customer.
--   * No business_segment (none analyst-supplied).
--
-- Identifiers snake_case unquoted (rule S1). PascalCase display names are a Power BI
-- model-layer concern, applied there, not in this SQL.
--
-- 6 ENTITY dims each carry an unknown member at _sk = -1 (fact FKs COALESCE to -1).
-- dim_date carries NO -1 member (marked date table, rule S8): an unmatched fact date
-- is rejected by date_sk NOT NULL, never absorbed by a sentinel.
-- Idempotent: drop fact before dims (FK order), recreate all in one transaction.
-- Save UTF-8 without BOM (English labels only here).

SET client_encoding TO 'UTF8';

BEGIN;

CREATE SCHEMA IF NOT EXISTS gold;

-- FK dependency order: fact first.
DROP TABLE IF EXISTS gold.fct_sales;
DROP TABLE IF EXISTS gold.dim_product;
DROP TABLE IF EXISTS gold.dim_customer;
DROP TABLE IF EXISTS gold.dim_salesperson;
DROP TABLE IF EXISTS gold.dim_product_purchaser;
DROP TABLE IF EXISTS gold.dim_billing_type;
DROP TABLE IF EXISTS gold.dim_branch;
DROP TABLE IF EXISTS gold.dim_date;

-- ============================================================ dim_product
CREATE TABLE gold.dim_product (
  product_sk   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id   TEXT,                 -- natural key
  product_name TEXT,
  brand        TEXT,
  category     TEXT,
  subcategory  TEXT,
  segment      TEXT,
  division     TEXT,
  cluster      TEXT
);
INSERT INTO gold.dim_product OVERRIDING SYSTEM VALUE
  VALUES (-1,'UNKNOWN','Unknown','Unknown','Unknown','Unknown','Unknown','Unknown','Unknown');
-- product_id -> attributes verified 1:1 (material<->material_desc 9,690<->9,690); max() safe.
INSERT INTO gold.dim_product
  (product_id, product_name, brand, category, subcategory, segment, division, cluster)
SELECT product_id, max(product_name), max(brand), max(category),
       max(subcategory), max(segment), max(division), max(cluster)
FROM silver.sales_c086
GROUP BY product_id;

-- ============================================================ dim_customer (keyed on the clean id)
CREATE TABLE gold.dim_customer (
  customer_sk   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   TEXT,               -- holds customer_id_clean ('WALK_IN' for site-code rows)
  customer_name TEXT
);
INSERT INTO gold.dim_customer OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown');
-- keyed on customer_id_clean: the 85,911 walk-in rows collapse to one 'WALK_IN' member,
-- NOT a member literally named 'C086' (the site code).
INSERT INTO gold.dim_customer (customer_id, customer_name)
SELECT customer_id_clean, max(customer_name)
FROM silver.sales_c086
WHERE customer_id_clean IS NOT NULL
GROUP BY customer_id_clean;

-- ============================================================ dim_salesperson
CREATE TABLE gold.dim_salesperson (
  salesperson_sk       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  salesperson_id       TEXT,
  salesperson_name     TEXT,
  salesperson_position TEXT
);
INSERT INTO gold.dim_salesperson OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown','Unknown');
-- blank salesperson_id rows (NULL, ~1,748) fold into the -1 member (excluded here).
INSERT INTO gold.dim_salesperson (salesperson_id, salesperson_name, salesperson_position)
SELECT salesperson_id, max(salesperson_name), max(salesperson_position)
FROM silver.sales_c086
WHERE salesperson_id IS NOT NULL
GROUP BY salesperson_id;

-- ============================================================ dim_product_purchaser (NEW -- counter agent)
CREATE TABLE gold.dim_product_purchaser (
  purchaser_sk      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_purchaser TEXT
);
INSERT INTO gold.dim_product_purchaser OVERRIDING SYSTEM VALUE VALUES (-1,'Unknown');
INSERT INTO gold.dim_product_purchaser (product_purchaser)
SELECT product_purchaser
FROM silver.sales_c086
WHERE product_purchaser IS NOT NULL
GROUP BY product_purchaser;

-- ============================================================ dim_billing_type
CREATE TABLE gold.dim_billing_type (
  billing_type_sk    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billing_type_code  TEXT,
  billing_type_label TEXT,
  is_return          BOOLEAN
);
INSERT INTO gold.dim_billing_type OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown',FALSE);
INSERT INTO gold.dim_billing_type (billing_type_code, billing_type_label, is_return)
SELECT billing_type_code, max(billing_type_label), bool_or(is_return)
FROM silver.sales_c086 GROUP BY billing_type_code;

-- ============================================================ dim_branch
CREATE TABLE gold.dim_branch (
  branch_sk   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id   TEXT,
  branch_name TEXT
);
INSERT INTO gold.dim_branch OVERRIDING SYSTEM VALUE VALUES (-1,'UNKNOWN','Unknown');
INSERT INTO gold.dim_branch (branch_id, branch_name)
SELECT branch_id, max(branch_name) FROM silver.sales_c086 GROUP BY branch_id;

-- ============================================================ dim_date (contiguous; NO -1 member)
CREATE TABLE gold.dim_date (
  date_sk    INT PRIMARY KEY,             -- smart key YYYYMMDD
  full_date  DATE,
  year       SMALLINT,
  quarter    SMALLINT,
  month      SMALLINT,
  month_name TEXT,
  day        SMALLINT,
  day_name   TEXT,
  iso_week   SMALLINT,
  is_weekend BOOLEAN
);
-- NO -1 unknown member: dim_date is a MARKED date table (Power BI validates it as
-- unique/contiguous/no-nulls). A -1/NULL member would break marking it (rule S8 / D10).
-- An unmatched fact date is handled by date_sk NOT NULL on the fact (fail loud).
INSERT INTO gold.dim_date
SELECT
  (to_char(d,'YYYYMMDD'))::int       AS date_sk,
  d::date                            AS full_date,
  extract(year FROM d)::smallint,
  extract(quarter FROM d)::smallint,
  extract(month FROM d)::smallint,
  to_char(d,'Month'),
  extract(day FROM d)::smallint,
  to_char(d,'Day'),
  extract(week FROM d)::smallint,
  (extract(isodow FROM d) >= 6)      AS is_weekend
FROM generate_series(DATE '2023-01-01', DATE '2025-12-31', INTERVAL '1 day') AS g(d);

-- ============================================================ fct_sales
CREATE TABLE gold.fct_sales (
  sale_sk           BIGINT PRIMARY KEY,        -- surrogate PK, carried from silver
  -- degenerate dimensions (live on the fact)
  invoice           TEXT,                      -- per-invoice reference (reference_no)
  -- foreign keys to dims
  product_sk        INT NOT NULL,
  customer_sk       INT NOT NULL,
  salesperson_sk    INT NOT NULL,
  purchaser_sk      INT NOT NULL,
  date_sk           INT NOT NULL,
  billing_type_sk   INT NOT NULL,
  branch_sk         INT NOT NULL,
  -- measures (2)
  gross_sales       NUMERIC(18,2),
  quantity          NUMERIC(18,3),
  is_return         BOOLEAN
);
INSERT INTO gold.fct_sales
  (sale_sk, invoice,
   product_sk, customer_sk, salesperson_sk, purchaser_sk, date_sk, billing_type_sk, branch_sk,
   gross_sales, quantity, is_return)
SELECT
  s.sale_sk, s.invoice,
  COALESCE(dp.product_sk, -1),
  COALESCE(dc.customer_sk, -1),
  COALESCE(dsp.salesperson_sk, -1),
  COALESCE(dpp.purchaser_sk, -1),
  dd.date_sk,   -- NO COALESCE to -1: an unmatched/NULL fact date yields NULL and is
                -- rejected by date_sk NOT NULL (fail loud -- a calendar-coverage bug).
  COALESCE(dbt.billing_type_sk, -1),
  COALESCE(db.branch_sk, -1),
  s.gross_sales, s.quantity, s.is_return
FROM silver.sales_c086 s
LEFT JOIN gold.dim_product           dp  ON dp.product_id        = s.product_id
LEFT JOIN gold.dim_customer          dc  ON dc.customer_id       = s.customer_id_clean
LEFT JOIN gold.dim_salesperson       dsp ON dsp.salesperson_id   = s.salesperson_id
LEFT JOIN gold.dim_product_purchaser dpp ON dpp.product_purchaser = s.product_purchaser
LEFT JOIN gold.dim_date              dd  ON dd.full_date         = s.sale_date
LEFT JOIN gold.dim_billing_type      dbt ON dbt.billing_type_code = s.billing_type_code
LEFT JOIN gold.dim_branch            db  ON db.branch_id         = s.branch_id;

-- FK constraints (after load, so the -1 members and rows exist first)
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_product      FOREIGN KEY (product_sk)      REFERENCES gold.dim_product (product_sk);
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_customer     FOREIGN KEY (customer_sk)     REFERENCES gold.dim_customer (customer_sk);
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_salesperson  FOREIGN KEY (salesperson_sk)  REFERENCES gold.dim_salesperson (salesperson_sk);
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_purchaser    FOREIGN KEY (purchaser_sk)    REFERENCES gold.dim_product_purchaser (purchaser_sk);
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_date         FOREIGN KEY (date_sk)         REFERENCES gold.dim_date (date_sk);
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_billing_type FOREIGN KEY (billing_type_sk) REFERENCES gold.dim_billing_type (billing_type_sk);
ALTER TABLE gold.fct_sales ADD CONSTRAINT fk_fct_branch       FOREIGN KEY (branch_sk)       REFERENCES gold.dim_branch (branch_sk);

-- indexes on FKs for star-join performance
CREATE INDEX idx_fct_product_sk      ON gold.fct_sales (product_sk);
CREATE INDEX idx_fct_customer_sk     ON gold.fct_sales (customer_sk);
CREATE INDEX idx_fct_salesperson_sk  ON gold.fct_sales (salesperson_sk);
CREATE INDEX idx_fct_purchaser_sk    ON gold.fct_sales (purchaser_sk);
CREATE INDEX idx_fct_date_sk         ON gold.fct_sales (date_sk);
CREATE INDEX idx_fct_billing_type_sk ON gold.fct_sales (billing_type_sk);
CREATE INDEX idx_fct_branch_sk       ON gold.fct_sales (branch_sk);

COMMIT;
