-- 0001_create_gold_sales_c086_star.sql
-- Build the gold Kimball star over silver.sales_c086_raw.
--
-- Power BI reads gold. One fact (billing-document line-item grain) + 4 conformed
-- dims + dim_date. Surrogate _sk keys (GENERATED ... IDENTITY), natural keys
-- retained, an unknown member (_sk = -1) in every ENTITY dim (fact FKs COALESCE
-- missing lookups to -1); the DATE dim carries NO -1 member (marked date table,
-- rule S8) -- an unmatched fact date is rejected by date_sk NOT NULL, not
-- absorbed by a sentinel. reference_no + item_no are DEGENERATE dims: they live
-- on the fact (they are also the declared grain key).
--
-- Per the approved mappings/sales_c086_raw/source-map.yaml gold_star section:
--   fact:    gold.fct_sales_c086 (quantity, gross_sales only -- no net_sales,
--            no tax/discount columns; CLOSED 2026-07-16, gross_sales is the
--            standing "sales" measure, see source-map.yaml derived_columns)
--   dims:    dim_product_c086, dim_billing_type_c086, dim_customer_c086,
--            dim_staff_c086, dim_date_c086
--   (dim_purchaser_c086 was designed earlier in the same session then removed
--   when buyer/purchaser was dropped from the model entirely -- see
--   source-map.yaml for that column's full history. Not built here.)
--
-- Idempotent: drop fact before dims (FK order), recreate all in one transaction.
-- ASCII only (English labels, billing_type already translated in silver);
-- UTF-8 no BOM. dim_date span 2023-01-01..2025-12-31 (from the approved
-- source-map.yaml; covers every sale_date contiguously, verified against the
-- live silver min/max before writing this file).

SET client_encoding TO 'UTF8';

BEGIN;

CREATE SCHEMA IF NOT EXISTS gold;

-- FK dependency order: fact first.
DROP TABLE IF EXISTS gold.fct_sales_c086;
DROP TABLE IF EXISTS gold.dim_product_c086;
DROP TABLE IF EXISTS gold.dim_billing_type_c086;
DROP TABLE IF EXISTS gold.dim_customer_c086;
DROP TABLE IF EXISTS gold.dim_staff_c086;
DROP TABLE IF EXISTS gold.dim_date_c086;

-- ============================================================ dim_product_c086
-- material is the natural key; the rest are its 1:1/flat-denorm attributes
-- (all verified 1:1 with material in source-profile.md -- 0 fan-out).
-- Excludes material='UNKNOWN' from the natural population for the same reason
-- documented in dim_staff_c086 below (a real dim row sharing the -1 sentinel's
-- label would silently duplicate facts via a 1:many join). Verified 0 such
-- rows exist today (material is 0% blank in this table), but the exclusion is
-- kept as a standing safeguard against a future bronze reload introducing one.
CREATE TABLE gold.dim_product_c086 (
  product_sk    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material      TEXT,                    -- natural key
  material_desc TEXT,
  category      TEXT,
  subcategory   TEXT,
  segment       TEXT,
  division      TEXT,
  brand         TEXT,
  item_cluster  TEXT
);
INSERT INTO gold.dim_product_c086 OVERRIDING SYSTEM VALUE
  VALUES (-1, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', 'UNKNOWN');
INSERT INTO gold.dim_product_c086
  (material, material_desc, category, subcategory, segment, division, brand, item_cluster)
SELECT
  material,
  max(material_desc) AS material_desc,  -- 1:1 verified; max() is a safe collapse
  max(category)       AS category,
  max(subcategory)    AS subcategory,
  max(segment)        AS segment,
  max(division)       AS division,
  max(brand)          AS brand,
  max(item_cluster)   AS item_cluster
FROM silver.sales_c086_raw
WHERE material <> 'UNKNOWN'    -- see dim_staff_c086 note: sentinel maps to -1, not a real row
GROUP BY material;

-- ============================================================ dim_billing_type_c086
-- billing_type (English, translated in silver) is the natural key; billing_type_code
-- (FP/Z1..Z10) is its 1:1 short-code attribute (RC10). Same sentinel-exclusion
-- safeguard as dim_product_c086/dim_staff_c086 (verified 0 such rows today).
CREATE TABLE gold.dim_billing_type_c086 (
  billing_type_sk   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billing_type      TEXT,
  billing_type_code TEXT
);
INSERT INTO gold.dim_billing_type_c086 OVERRIDING SYSTEM VALUE
  VALUES (-1, 'UNKNOWN', 'UNKNOWN');
INSERT INTO gold.dim_billing_type_c086 (billing_type, billing_type_code)
SELECT billing_type, max(billing_type_code)
FROM silver.sales_c086_raw
WHERE billing_type <> 'UNKNOWN'
GROUP BY billing_type;

-- ============================================================ dim_customer_c086
-- customer is the natural key; customer_name is its 1:1 attribute. PII ruled
-- low-risk 2026-07-16 (predominantly B2B/institutional names) -- kept as-is.
-- Same sentinel-exclusion safeguard as the dims above (verified 0 such rows
-- today).
CREATE TABLE gold.dim_customer_c086 (
  customer_sk   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer      TEXT,
  customer_name TEXT
);
INSERT INTO gold.dim_customer_c086 OVERRIDING SYSTEM VALUE
  VALUES (-1, 'UNKNOWN', 'UNKNOWN');
INSERT INTO gold.dim_customer_c086 (customer, customer_name)
SELECT customer, max(customer_name)
FROM silver.sales_c086_raw
WHERE customer <> 'UNKNOWN'
GROUP BY customer;

-- ============================================================ dim_staff_c086
-- staff_code is the natural key; staff_name_masked (md5 pseudonym, PII ruling
-- 2026-07-16) and staff_position are its attributes.
--
-- BUG FOUND AND FIXED (2026-07-16, during the first live run of this
-- migration): silver's missing-value policy coalesces a blank staff_code to
-- the literal string 'UNKNOWN' (1,745 rows -- the known 0.70% personel_number
-- blank rate). Building this dim with a plain `GROUP BY staff_code` therefore
-- produced a REAL dimension row for staff_code='UNKNOWN' in ADDITION to the
-- manually-inserted -1 sentinel row (which ALSO uses the literal string
-- 'UNKNOWN') -- two dimension rows sharing one natural-key value. Every one of
-- those 1,745 silver rows then fanned out across BOTH matching dimension rows
-- in the fact LEFT JOIN below, silently duplicating fact rows (caught only
-- because the grain-key UNIQUE constraint failed on one such duplicated pair,
-- C0860010004024/5 -- reproduced deterministically on a second run, confirmed
-- as a real bug, not a query-nondeterminism fluke). FIX: exclude the sentinel
-- value from the natural-key population below; every staff_code='UNKNOWN' row
-- now correctly COALESCEs to the single -1 unknown member in the fact load,
-- same as a genuinely NULL/unmatched staff_code would.
CREATE TABLE gold.dim_staff_c086 (
  staff_sk          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_code        TEXT,
  staff_name_masked TEXT,
  staff_position    TEXT
);
INSERT INTO gold.dim_staff_c086 OVERRIDING SYSTEM VALUE
  VALUES (-1, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN');
INSERT INTO gold.dim_staff_c086 (staff_code, staff_name_masked, staff_position)
SELECT staff_code, max(staff_name_masked), max(staff_position)
FROM silver.sales_c086_raw
WHERE staff_code <> 'UNKNOWN'    -- exclude the sentinel; it maps to -1, not a real row
GROUP BY staff_code;

-- ============================================================ dim_date_c086 (contiguous)
CREATE TABLE gold.dim_date_c086 (
  date_sk    INT PRIMARY KEY,            -- smart key YYYYMMDD
  full_date  DATE,
  year       SMALLINT,
  quarter    SMALLINT,
  month      SMALLINT,
  month_name TEXT,
  day        SMALLINT,
  day_name   TEXT,
  iso_week   SMALLINT,
  is_weekend BOOLEAN
);
-- NO -1 unknown member: dim_date_c086 is a MARKED date table (dataCategory:
-- Time), which Power BI validates as unique/contiguous/NO-nulls. A -1/NULL
-- member would break that (rule S8). An unmatched fact date is handled by
-- date_sk NOT NULL below (the load fails loudly), never by a sentinel member.
-- CONTIGUOUS calendar over the full span (RC15; never SELECT DISTINCT date).
-- Span verified against the live silver.sales_c086_raw min/max (2023-01-01 ..
-- 2025-12-31, 0 NULL sale_date rows) before this migration was written.
INSERT INTO gold.dim_date_c086
SELECT
  (to_char(d,'YYYYMMDD'))::int       AS date_sk,
  d::date                             AS full_date,
  extract(year FROM d)::smallint,
  extract(quarter FROM d)::smallint,
  extract(month FROM d)::smallint,
  to_char(d,'Month'),
  extract(day FROM d)::smallint,
  to_char(d,'Day'),
  extract(week FROM d)::smallint,
  (extract(isodow FROM d) >= 6)       AS is_weekend
FROM generate_series(DATE '2023-01-01', DATE '2025-12-31', INTERVAL '1 day') AS g(d);

-- ============================================================ fct_sales_c086
CREATE TABLE gold.fct_sales_c086 (
  fct_sales_c086_sk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- degenerate dimensions (live on the fact; also the declared grain key)
  reference_no      TEXT NOT NULL,
  item_no           TEXT NOT NULL,
  is_return         BOOLEAN NOT NULL,     -- RC8 derived flag, carried through as-is
  -- foreign keys to dims
  product_sk        INT NOT NULL,
  billing_type_sk   INT NOT NULL,
  customer_sk       INT NOT NULL,
  staff_sk          INT NOT NULL,
  date_sk           INT NOT NULL,
  -- measures (CLOSED 2026-07-16: gross_sales IS the standing "sales" measure;
  -- no net_sales, no tax/discount columns -- all dropped from the model)
  quantity          NUMERIC(14,3),
  gross_sales       NUMERIC(18,2)
);
INSERT INTO gold.fct_sales_c086
  (reference_no, item_no, is_return,
   product_sk, billing_type_sk, customer_sk, staff_sk, date_sk,
   quantity, gross_sales)
SELECT
  s.reference_no, s.item_no, s.is_return,
  COALESCE(dp.product_sk, -1),
  COALESCE(dbt.billing_type_sk, -1),
  COALESCE(dc.customer_sk, -1),
  COALESCE(dst.staff_sk, -1),
  dd.date_sk,   -- NO COALESCE to a -1 date member: an unmatched/NULL fact date
                -- yields NULL and is rejected by date_sk NOT NULL (fail loud,
                -- a real calendar-coverage bug), never silently bucketed
  s.quantity, s.gross_sales
FROM silver.sales_c086_raw s
LEFT JOIN gold.dim_product_c086      dp  ON dp.material          = s.material
LEFT JOIN gold.dim_billing_type_c086 dbt ON dbt.billing_type      = s.billing_type
LEFT JOIN gold.dim_customer_c086     dc  ON dc.customer           = s.customer
LEFT JOIN gold.dim_staff_c086        dst ON dst.staff_code        = s.staff_code
LEFT JOIN gold.dim_date_c086         dd  ON dd.full_date          = s.sale_date;

-- Declared grain (map: one row = one billing-document line item,
-- PK (reference_no, item_no)). The surrogate fct_sales_c086_sk is the physical
-- PK, but the DECLARED business key must be physically enforced too, or a
-- double-insert / partial re-run would silently duplicate every fact row with
-- no constraint failing. Added after load, alongside the FK constraints.
ALTER TABLE gold.fct_sales_c086 ADD CONSTRAINT uq_fct_c086_grain UNIQUE (reference_no, item_no);

-- FK constraints (after load, so the -1 members and rows exist)
ALTER TABLE gold.fct_sales_c086 ADD CONSTRAINT fk_fct_c086_product      FOREIGN KEY (product_sk)      REFERENCES gold.dim_product_c086 (product_sk);
ALTER TABLE gold.fct_sales_c086 ADD CONSTRAINT fk_fct_c086_billing_type FOREIGN KEY (billing_type_sk) REFERENCES gold.dim_billing_type_c086 (billing_type_sk);
ALTER TABLE gold.fct_sales_c086 ADD CONSTRAINT fk_fct_c086_customer     FOREIGN KEY (customer_sk)     REFERENCES gold.dim_customer_c086 (customer_sk);
ALTER TABLE gold.fct_sales_c086 ADD CONSTRAINT fk_fct_c086_staff        FOREIGN KEY (staff_sk)        REFERENCES gold.dim_staff_c086 (staff_sk);
ALTER TABLE gold.fct_sales_c086 ADD CONSTRAINT fk_fct_c086_date         FOREIGN KEY (date_sk)         REFERENCES gold.dim_date_c086 (date_sk);

-- indexes on FKs for star-join performance
CREATE INDEX idx_fct_c086_product_sk      ON gold.fct_sales_c086 (product_sk);
CREATE INDEX idx_fct_c086_billing_type_sk ON gold.fct_sales_c086 (billing_type_sk);
CREATE INDEX idx_fct_c086_customer_sk     ON gold.fct_sales_c086 (customer_sk);
CREATE INDEX idx_fct_c086_staff_sk        ON gold.fct_sales_c086 (staff_sk);
CREATE INDEX idx_fct_c086_date_sk         ON gold.fct_sales_c086 (date_sk);

COMMIT;
