table _Measures
	lineageTag: b0c1d2e3-4f56-47a8-9b0c-1d2e3f4a5b6c

	/// Total sales after returns. Return lines carry negative gross_sales, so a plain SUM is already net.
	measure NetSales = SUM ( 'gold fct_sales'[gross_sales] )
		formatString: #,0.00
		displayFolder: Sales
		lineageTag: 4ff13413-e16a-4431-a90a-fd1083aacae7

	/// Sales from kept (non-return) lines only, before returns net out.
	measure GrossSales = CALCULATE ( [NetSales], 'gold fct_sales'[is_return] = FALSE () )
		formatString: #,0.00
		displayFolder: Sales
		lineageTag: e3a94c5c-4e2b-4c57-8607-de7fef329ceb

	/// Money value of returned lines. Negative by design; GrossSales + Returns = NetSales.
	measure Returns = CALCULATE ( [NetSales], 'gold fct_sales'[is_return] = TRUE () )
		formatString: #,0.00
		displayFolder: Sales
		lineageTag: 1d8f6cf0-c0e5-4f08-a79d-7464c5569f7e

	/// Units sold, net of returned units (quantity is signed: returns negative). Fractional part-packs allowed.
	measure TotalUnits = SUMX ( 'gold fct_sales', 'gold fct_sales'[quantity] )
		formatString: #,0.000
		displayFolder: Sales
		lineageTag: f21d6341-2b13-4810-935c-0bba0ef6c9b7

	/// Return money as a share of gross sales (value-weighted return rate). ABS applied here, not in Returns.
	measure ReturnValueRate = DIVIDE ( ABS ( [Returns] ), [GrossSales] )
		formatString: 0.00%
		displayFolder: Returns
		lineageTag: 8bcd0c1c-8577-44e5-8146-c119a154a0b9

	/// Share of sale lines that were returns (count-based return frequency).
	measure LineReturnRate =
			DIVIDE (
			    CALCULATE ( COUNTROWS ( 'gold fct_sales' ), 'gold fct_sales'[is_return] = TRUE () ),
			    COUNTROWS ( 'gold fct_sales' )
			)
		formatString: 0.00%
		displayFolder: Returns
		lineageTag: bb779d89-a275-4f00-ae73-1ac9f1c511d3

	/// Distinct invoices (baskets), including return-only invoices.
	measure Transactions = DISTINCTCOUNT ( 'gold fct_sales'[invoice] )
		formatString: #,0
		displayFolder: Basket
		lineageTag: df0cc942-a04e-468d-b637-186032a052a4

	/// Distinct invoices with at least one non-return line; all-return baskets excluded. Verify live.
	measure SaleTransactions =
			CALCULATE (
			    DISTINCTCOUNT ( 'gold fct_sales'[invoice] ),
			    'gold fct_sales'[is_return] = FALSE ()
			)
		formatString: #,0
		displayFolder: Basket
		lineageTag: 0a3df151-58c7-480d-acb2-b679fe14d835

	/// Net sales per transaction (average basket value).
	measure AverageOrderValue = DIVIDE ( [NetSales], [Transactions] )
		formatString: #,0.00
		displayFolder: Basket
		lineageTag: 556c0041-a1df-455d-b3f3-625f97b2752c

	/// Net units per transaction (average items per basket).
	measure UnitsPerBasket = DIVIDE ( [TotalUnits], [Transactions] )
		formatString: #,0.000
		displayFolder: Basket
		lineageTag: e1895780-c386-4b0c-8503-b4c8729e4afc

	/// Net sales per line item across all fact rows (returns in the denominator).
	measure AverageLineValue = DIVIDE ( [NetSales], COUNTROWS ( 'gold fct_sales' ) )
		formatString: #,0.00
		displayFolder: Basket
		lineageTag: 28c3e6d6-37f3-4a8d-8cdd-3e7fc572a09c

	/// Distinct customer keys on the fact, including the single WALK_IN anonymous member.
	measure ActiveCustomers = DISTINCTCOUNT ( 'gold fct_sales'[customer_sk] )
		formatString: #,0
		displayFolder: Customer
		lineageTag: 98c7f0e4-baf3-4466-8940-99b1f63b183a

	/// Distinct identified customers; WALK_IN and the -1 unknown removed.
	measure NamedCustomers =
			CALCULATE (
			    DISTINCTCOUNT ( 'gold fct_sales'[customer_sk] ),
			    'gold dim_customer'[customer_id] <> "WALK_IN",
			    'gold dim_customer'[customer_sk] <> -1
			)
		formatString: #,0
		displayFolder: Customer
		lineageTag: b086c8d5-f631-4621-87b3-23126b222d9a

	/// Net sales from identified customers only (already net of returns).
	measure NamedCustomerSales =
			CALCULATE (
			    [NetSales],
			    'gold dim_customer'[customer_id] <> "WALK_IN",
			    'gold dim_customer'[customer_sk] <> -1
			)
		formatString: #,0.00
		displayFolder: Customer
		lineageTag: fb1fc193-6c16-45c0-9699-89b8880acb5a

	/// Average net sales per identified customer.
	measure SalesPerNamedCustomer = DIVIDE ( [NamedCustomerSales], [NamedCustomers] )
		formatString: #,0.00
		displayFolder: Customer
		lineageTag: ed10e07a-691c-41f6-ba5b-1a42fc5f4d44

	/// Share of total net sales from the anonymous WALK_IN aggregate. Use as a card, not a per-customer column.
	measure WalkInSalesShare =
			VAR WalkInNet = CALCULATE ( [NetSales], 'gold dim_customer'[customer_id] = "WALK_IN" )
			VAR TotalNet = CALCULATE ( [NetSales], ALL ( 'gold dim_customer' ) )
			RETURN DIVIDE ( WalkInNet, TotalNet )
		formatString: 0.00%
		displayFolder: Customer
		lineageTag: 74982ccc-ee16-450e-ac2c-62adb9e65325

	/// Net sales for the same period one year earlier (comparison baseline). Anchors on the marked date table.
	measure NetSalesPriorYear = CALCULATE ( [NetSales], SAMEPERIODLASTYEAR ( 'gold dim_date'[full_date] ) )
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 17183b5b-4aa4-42f0-82c4-e0fd01719492

	/// Year-over-year % change in net sales; blank when no prior year exists. Meaningful at year grain.
	measure NetSalesYoY = DIVIDE ( [NetSales] - [NetSalesPriorYear], [NetSalesPriorYear] )
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 420b9679-f4e9-41be-96b5-805dfda4cf5d

	/// Net sales accumulated Jan 1 to latest date in view; resets each year.
	measure NetSalesYTD = CALCULATE ( [NetSales], DATESYTD ( 'gold dim_date'[full_date] ) )
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 876a8f75-4cdc-420c-affc-4c1cb7fea3e3

	/// Month-over-month % change; blank for first month. Month grain only.
	measure NetSalesMoM =
			DIVIDE (
			    [NetSales] - CALCULATE ( [NetSales], DATEADD ( 'gold dim_date'[full_date], -1, MONTH ) ),
			    CALCULATE ( [NetSales], DATEADD ( 'gold dim_date'[full_date], -1, MONTH ) )
			)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: f72aea7c-2d6f-4e9f-9bce-728638849c7f

	/// Trailing 3-month net sales ending at the latest date in view (smoothed short-run trend).
	measure NetSales3MonthRolling =
			CALCULATE (
			    [NetSales],
			    DATESINPERIOD ( 'gold dim_date'[full_date], MAX ( 'gold dim_date'[full_date] ), -3, MONTH )
			)
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 34e8859b-570a-4ca5-90a0-8eb118aca1a7

	/// Distinct products with at least one sale line, excluding the -1 unknown. Verify 9,669 live.
	measure ProductCountSold =
			CALCULATE (
			    DISTINCTCOUNT ( 'gold fct_sales'[product_sk] ),
			    'gold fct_sales'[product_sk] <> -1
			)
		formatString: #,0
		displayFolder: Product
		lineageTag: 073548f6-2fb3-4a84-abe0-d81ab6d2109c

	/// Each division's share of net sales, re-based to the visible divisions.
	measure SalesMixPctByDivision =
			DIVIDE (
			    [NetSales],
			    CALCULATE ( [NetSales], ALLSELECTED ( 'gold dim_product'[division] ) )
			)
		formatString: 0.00%
		displayFolder: Product
		lineageTag: e80970e7-717e-4baa-90eb-93a1c5fba413

	/// Name (text label) of the single best-selling product by net sales.
	measure TopProductByNetSales =
			VAR TopSK = TOPN ( 1, VALUES ( 'gold dim_product'[product_sk] ), [NetSales], DESC )
			RETURN CALCULATE ( SELECTEDVALUE ( 'gold dim_product'[product_name] ), TopSK )
		displayFolder: Product
		lineageTag: 0868a7f7-f62e-4647-a4f4-a5871721f234

	/// Average net sales per distinct product sold (denominator is products that sold, not catalog size).
	measure SalesPerProduct = DIVIDE ( [NetSales], [ProductCountSold] )
		formatString: #,0.00
		displayFolder: Product
		lineageTag: 6aba270e-5b02-469b-841f-63001559c3bf

	/// Share of net sales from the top 20% of products (Pareto class A). 20% threshold is a business convention.
	measure ABCClassAShare =
			VAR N = ROUNDUP ( [ProductCountSold] * 0.2, 0 )
			VAR TopProducts = TOPN ( N, VALUES ( 'gold dim_product'[product_sk] ), [NetSales], DESC )
			RETURN DIVIDE ( CALCULATE ( [NetSales], TopProducts ), [NetSales] )
		formatString: 0.00%
		displayFolder: Product
		lineageTag: d1527c19-aa7f-4382-94ab-3f1dbf5f4727

	/// Distinct real salespeople with at least one sale line (excludes the -1 unknown).
	measure ActiveSalespeople =
			CALCULATE (
			    DISTINCTCOUNT ( 'gold fct_sales'[salesperson_sk] ),
			    'gold fct_sales'[salesperson_sk] <> -1
			)
		formatString: #,0
		displayFolder: Staff
		lineageTag: 8456e8b0-d5c0-4ac4-852c-c1a802d3c06c

	/// Average net sales per active salesperson (-1 unknown excluded from the count).
	measure SalesPerSalesperson =
			DIVIDE (
			    [NetSales],
			    CALCULATE ( DISTINCTCOUNT ( 'gold fct_sales'[salesperson_sk] ), 'gold fct_sales'[salesperson_sk] <> -1 )
			)
		formatString: #,0.00
		displayFolder: Staff
		lineageTag: ebffe5fe-83b2-446f-ba71-5f5d7d909699

	/// Average net sales per counter agent (product purchaser); 16 real agents.
	measure SalesPerCounterAgent =
			DIVIDE (
			    [NetSales],
			    CALCULATE ( DISTINCTCOUNT ( 'gold fct_sales'[purchaser_sk] ), 'gold fct_sales'[purchaser_sk] <> -1 )
			)
		formatString: #,0.00
		displayFolder: Staff
		lineageTag: b501cd4b-427d-409a-bf85-a90074588d67

	/// Share of net sales on weekend days (Sat/Sun), from the marked date table's is_weekend flag.
	measure WeekendSalesShare =
			DIVIDE (
			    CALCULATE ( [NetSales], 'gold dim_date'[is_weekend] = TRUE () ),
			    [NetSales]
			)
		formatString: 0.00%
		displayFolder: Segment
		lineageTag: d8e2cd04-7f06-4a8a-9da5-219043bb98fe

	column Value
		isHidden
		formatString: 0
		lineageTag: c1d2e3f4-5a67-48b9-ac1d-2e3f4a5b6c7d
		summarizeBy: sum
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = {BLANK()}

	annotation PBI_Id = a1b2c3d4e5f6
