table 'gold fct_sales'
	lineageTag: 617870f5-cdbc-471f-93e4-db7df64da979

	/// Gross sales amount (sum of sales_amount).
	measure TotalSales = SUM('gold fct_sales'[sales_amount])
		formatString: #,0.00
		displayFolder: Sales
		lineageTag: fd7e63a2-fa60-44e1-a1bc-f75b78ec12c1

	/// Net sales amount after discounts (sum of net_amount).
	measure NetSales = SUM('gold fct_sales'[net_amount])
		formatString: #,0.00
		displayFolder: Sales
		lineageTag: 03a3c7c3-ddb9-4f2d-9813-d863a11d7974

	/// Total tax (sum of tax_amount).
	measure TotalTax = SUM('gold fct_sales'[tax_amount])
		formatString: #,0.00
		displayFolder: Sales
		lineageTag: a361e1d6-00d0-4588-8c0d-bd2bf8d8116c

	/// Total discount (sum of discount_amount).
	measure TotalDiscount = SUM('gold fct_sales'[discount_amount])
		formatString: #,0.00
		displayFolder: Sales
		lineageTag: ef7b7587-751c-4ee2-adea-8a09bc51e39a

	/// Total quantity sold (sum of quantity).
	measure TotalQuantity = SUM('gold fct_sales'[quantity])
		formatString: #,0.0000
		displayFolder: Sales
		lineageTag: 16ca90e4-6e3f-4587-baa9-b3cb14f8f4a1

	/// Number of invoice line items.
	measure SalesLineCount = COUNTROWS('gold fct_sales')
		formatString: #,0
		displayFolder: Sales
		lineageTag: f9abbf3d-2a0b-4b3d-a657-a33f348a17a0

	/// Average gross sales per line item (DIVIDE-safe).
	measure AverageLineValue = DIVIDE([TotalSales], [SalesLineCount])
		formatString: #,0.00
		displayFolder: Ratios
		lineageTag: 0e9ed244-083c-4a48-bcab-374661e2a2fe

	/// Discount as a share of gross sales (DIVIDE-safe).
	measure DiscountRate = DIVIDE([TotalDiscount], [TotalSales])
		formatString: 0.0%
		displayFolder: Ratios
		lineageTag: 149c7c9e-ce87-4323-84f1-a2fec48b0aab

	/// Tax as a share of net sales (DIVIDE-safe).
	measure EffectiveTaxRate = DIVIDE([TotalTax], [NetSales])
		formatString: 0.0%
		displayFolder: Ratios
		lineageTag: 2355f5e5-e935-4786-8a05-c6567836041b

	/// Gross sales on return lines (is_return = TRUE).
	measure ReturnSales = CALCULATE([TotalSales], 'gold fct_sales'[is_return] = TRUE())
		formatString: #,0.00
		displayFolder: Returns
		lineageTag: 1d291448-88d2-47f7-95a2-720aaceded3d

	/// Returns as a share of gross sales (DIVIDE-safe).
	measure ReturnRate = DIVIDE([ReturnSales], [TotalSales])
		formatString: 0.0%
		displayFolder: Returns
		lineageTag: 135be455-ecea-4d30-807c-67cfaf1b1914

	/// Year-to-date gross sales (requires dim_date marked as date table).
	measure SalesYTD = TOTALYTD([TotalSales], 'gold dim_date'[full_date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b5b29ac4-aef8-4ab8-a5e2-4397a3f9ad19

	/// Prior-year gross sales (same period last year).
	measure SalesPY = CALCULATE([TotalSales], SAMEPERIODLASTYEAR('gold dim_date'[full_date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 178d0985-e44d-4aa1-9d72-9b819c037162

	/// Year-over-year sales growth percent (DIVIDE-safe).
	measure SalesYoYPct = DIVIDE([TotalSales] - [SalesPY], [SalesPY])
		formatString: 0.0%
		displayFolder: Time Intelligence
		lineageTag: b158ef5d-c6fd-4f1e-b9e9-a50c870183ec

	column fct_sales_sk
		dataType: int64
		formatString: 0
		lineageTag: 509a4185-80da-4a29-b495-aa272bc85939
		summarizeBy: none
		sourceColumn: fct_sales_sk

		annotation SummarizationSetBy = User

	column invoice_no
		dataType: string
		lineageTag: bd124b09-c1e9-4c42-94aa-0b05802c1a39
		summarizeBy: none
		sourceColumn: invoice_no

		annotation SummarizationSetBy = Automatic

	column line_no
		dataType: int64
		formatString: 0
		lineageTag: 79839cc7-e334-450c-aa9d-1710186f2753
		summarizeBy: none
		sourceColumn: line_no

		annotation SummarizationSetBy = User

	column original_invoice_ref
		dataType: string
		lineageTag: 7020e745-7596-4385-87c2-0768ee9b1383
		summarizeBy: none
		sourceColumn: original_invoice_ref

		annotation SummarizationSetBy = Automatic

	column product_sk
		dataType: int64
		formatString: 0
		lineageTag: 9558b831-cc75-43a6-bc15-6613221af0a8
		summarizeBy: none
		sourceColumn: product_sk

		annotation SummarizationSetBy = Automatic

	column customer_sk
		dataType: int64
		formatString: 0
		lineageTag: 75b3875a-7f4f-4ca6-8339-306881741337
		summarizeBy: none
		sourceColumn: customer_sk

		annotation SummarizationSetBy = Automatic

	column salesperson_sk
		dataType: int64
		formatString: 0
		lineageTag: cdc4b0bf-22fb-4a2a-8b21-9f897aed8ac3
		summarizeBy: none
		sourceColumn: salesperson_sk

		annotation SummarizationSetBy = Automatic

	column date_sk
		dataType: int64
		formatString: 0
		lineageTag: 1780be56-2413-4de0-9ba9-345f5e6e2b95
		summarizeBy: none
		sourceColumn: date_sk

		annotation SummarizationSetBy = Automatic

	column billing_type_sk
		dataType: int64
		formatString: 0
		lineageTag: 5cfd0747-da11-4568-9675-0eabb5c990ff
		summarizeBy: none
		sourceColumn: billing_type_sk

		annotation SummarizationSetBy = Automatic

	column branch_sk
		dataType: int64
		formatString: 0
		lineageTag: 77dfeb51-559a-49b4-a409-5bc96b97ceca
		summarizeBy: none
		sourceColumn: branch_sk

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		lineageTag: 5e265ca0-3f15-4649-8270-56e28bebe776
		summarizeBy: none
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_amount
		dataType: double
		lineageTag: ae34b96a-0f01-4289-9fac-d0d97eee43b9
		summarizeBy: none
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column net_amount
		dataType: double
		lineageTag: 02d15eb6-84ab-4fc9-a904-5e4c48b380da
		summarizeBy: none
		sourceColumn: net_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tax_amount
		dataType: double
		lineageTag: 58fdb0ff-4f3f-4ba9-8857-da2a7c157c0c
		summarizeBy: none
		sourceColumn: tax_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column discount_amount
		dataType: double
		lineageTag: 84ad4504-faf3-4042-802c-626e7bb182d9
		summarizeBy: none
		sourceColumn: discount_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_return
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2a44cb08-7f51-4f7e-8dd4-b2511b96efc0
		summarizeBy: none
		sourceColumn: is_return

		annotation SummarizationSetBy = Automatic

	partition 'gold fct_sales' = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database("db-pgsql-fra1-29712-do-user-33880537-0.a.db.ondigitalocean.com:25060", "ezaby_demo"),
				  #"Navigation 1" = Source{[Schema = "gold", Item = "fct_sales"]}[Data]
				in
				  #"Navigation 1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

