"""Unit tests for HR6 (RLS role contract binds to a real dim column)."""

from __future__ import annotations

from pathlib import Path

import pytest

from seshat.core import RuleContext, Severity
from seshat.rules.rls_access import check_rls_role_bindings

pytestmark = pytest.mark.unit

_REPO = Path(__file__).resolve().parents[2]

_FIXTURE_GOLD_SQL = (
    "CREATE SCHEMA IF NOT EXISTS gold;\n"
    "CREATE TABLE gold.dim_store (\n"
    "  store_sk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n"
    "  store_id TEXT,\n"
    "  region TEXT,\n"
    "  CONSTRAINT store_uq UNIQUE (store_id)\n"
    ");\n"
    "CREATE TABLE gold.fct_sales (\n"
    "  sale_sk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n"
    "  store_sk INT,\n"
    "  amount NUMERIC(10,2)\n"
    ");\n"
)


def _mig(tmp_path: Path, name: str, sql: str) -> str:
    rel = f"warehouse/migrations/{name}"
    dest = tmp_path / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(sql, encoding="utf-8")
    return rel


def _role(tmp_path: Path, table: str, name: str, yaml_text: str) -> str:
    rel = f"mappings/{table}/roles/{name}.yaml"
    dest = tmp_path / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(yaml_text, encoding="utf-8")
    return rel


def _ctx(tmp_path: Path, *rel: str) -> RuleContext:
    return RuleContext(repo_root=tmp_path, tracked_files=tuple(rel))


def _with_fixture_gold(tmp_path: Path) -> str:
    return _mig(tmp_path, "0001_gold.sql", _FIXTURE_GOLD_SQL)


_CLEAN_CONTRACT = (
    "name: RegionManager\n"
    "filter:\n"
    "  gold_table: gold.dim_store\n"
    "  column: region\n"
    "readiness:\n"
    "  status: pass\n"
    '  evidence: ["approved by owner on 2026-07-04"]\n'
    "  blocking_reasons: []\n"
)


# --- zero-contract case (Q-ZERO-ROLES, FR-010): absence emits nothing ---


def test_zero_contracts_emits_no_findings(tmp_path: Path) -> None:
    mig = _with_fixture_gold(tmp_path)
    ctx = _ctx(tmp_path, mig)
    assert list(check_rls_role_bindings(ctx)) == []


def test_passes_against_real_committed_tree() -> None:
    """The real repo tree has no committed rls-role-contract.yaml yet; HR6
    must emit zero findings against it (mirrors HR7's SC-001-style test)."""
    ctx = RuleContext(repo_root=_REPO, tracked_files=())
    assert list(check_rls_role_bindings(ctx)) == []


# --- US2: a well-formed role contract binds cleanly and clears HR6 ---


def test_well_formed_binding_produces_no_finding(tmp_path: Path) -> None:
    mig = _with_fixture_gold(tmp_path)
    role = _role(tmp_path, "sales", "RegionManager", _CLEAN_CONTRACT)
    ctx = _ctx(tmp_path, mig, role)
    assert list(check_rls_role_bindings(ctx)) == []


# --- US1: a declared role with no real filter binding fails the gate ---


def test_blank_filter_column_fails(tmp_path: Path) -> None:
    mig = _with_fixture_gold(tmp_path)
    contract = (
        "name: RegionManager\n"
        "filter:\n"
        "  gold_table: gold.dim_store\n"
        '  column: ""\n'
        "readiness:\n"
        "  status: not_started\n"
        "  evidence: []\n"
        "  blocking_reasons: []\n"
    )
    role = _role(tmp_path, "sales", "RegionManager", contract)
    ctx = _ctx(tmp_path, mig, role)
    findings = list(check_rls_role_bindings(ctx))
    assert len(findings) == 1
    assert findings[0].rule_id == "HR6"
    assert findings[0].severity is Severity.ERROR
    assert "RegionManager" in findings[0].message
    assert "filter.column" in findings[0].message


def test_nonexistent_gold_column_fails(tmp_path: Path) -> None:
    mig = _with_fixture_gold(tmp_path)
    contract = (
        "name: RegionManager\n"
        "filter:\n"
        "  gold_table: gold.dim_store\n"
        "  column: not_a_real_column\n"
        "readiness:\n"
        "  status: not_started\n"
        "  evidence: []\n"
        "  blocking_reasons: []\n"
    )
    role = _role(tmp_path, "sales", "RegionManager", contract)
    ctx = _ctx(tmp_path, mig, role)
    findings = list(check_rls_role_bindings(ctx))
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR
    assert "RegionManager" in findings[0].message
    assert "gold.dim_store" in findings[0].message
    assert "not_a_real_column" in findings[0].message


def test_silver_binding_fails(tmp_path: Path) -> None:
    mig = _with_fixture_gold(tmp_path)
    contract = (
        "name: RegionManager\n"
        "filter:\n"
        "  gold_table: silver.dim_store\n"
        "  column: region\n"
        "readiness:\n"
        "  status: not_started\n"
        "  evidence: []\n"
        "  blocking_reasons: []\n"
    )
    role = _role(tmp_path, "sales", "RegionManager", contract)
    ctx = _ctx(tmp_path, mig, role)
    findings = list(check_rls_role_bindings(ctx))
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR
    assert "silver.dim_store" in findings[0].message


def test_gold_table_absent_from_migrations_fails(tmp_path: Path) -> None:
    mig = _with_fixture_gold(tmp_path)
    contract = (
        "name: RegionManager\n"
        "filter:\n"
        "  gold_table: gold.dim_nonexistent\n"
        "  column: region\n"
        "readiness:\n"
        "  status: not_started\n"
        "  evidence: []\n"
        "  blocking_reasons: []\n"
    )
    role = _role(tmp_path, "sales", "RegionManager", contract)
    ctx = _ctx(tmp_path, mig, role)
    findings = list(check_rls_role_bindings(ctx))
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR
    assert "gold.dim_nonexistent" in findings[0].message


def test_fact_table_binding_hard_fails(tmp_path: Path) -> None:
    """Clarification C1: a gold.fct_* binding is Severity.ERROR, never
    Severity.WARNING -- a fact-bound role is the exact leak-through
    direction this feature exists to close."""
    mig = _with_fixture_gold(tmp_path)
    contract = (
        "name: RegionManager\n"
        "filter:\n"
        "  gold_table: gold.fct_sales\n"
        "  column: store_sk\n"
        "readiness:\n"
        "  status: not_started\n"
        "  evidence: []\n"
        "  blocking_reasons: []\n"
    )
    role = _role(tmp_path, "sales", "RegionManager", contract)
    ctx = _ctx(tmp_path, mig, role)
    findings = list(check_rls_role_bindings(ctx))
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR
    assert "dim" in findings[0].message.lower()
    assert "fact" in findings[0].message.lower()


# --- US3: readiness pass-with-no-evidence and duplicate-name loopholes ---


def test_pass_with_empty_evidence_fails(tmp_path: Path) -> None:
    mig = _with_fixture_gold(tmp_path)
    contract = (
        "name: RegionManager\n"
        "filter:\n"
        "  gold_table: gold.dim_store\n"
        "  column: region\n"
        "readiness:\n"
        "  status: pass\n"
        "  evidence: []\n"
        "  blocking_reasons: []\n"
    )
    role = _role(tmp_path, "sales", "RegionManager", contract)
    ctx = _ctx(tmp_path, mig, role)
    findings = list(check_rls_role_bindings(ctx))
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR
    assert "evidence" in findings[0].message.lower()


def test_duplicate_role_name_fails(tmp_path: Path) -> None:
    mig = _with_fixture_gold(tmp_path)
    contract_a = (
        "name: RegionManager\n"
        "filter:\n"
        "  gold_table: gold.dim_store\n"
        "  column: region\n"
        "readiness:\n"
        "  status: not_started\n"
        "  evidence: []\n"
        "  blocking_reasons: []\n"
    )
    contract_b = (
        "name: RegionManager\n"
        "filter:\n"
        "  gold_table: gold.dim_store\n"
        "  column: store_id\n"
        "readiness:\n"
        "  status: not_started\n"
        "  evidence: []\n"
        "  blocking_reasons: []\n"
    )
    role_a = _role(tmp_path, "sales", "RegionManagerA", contract_a)
    role_b = _role(tmp_path, "sales", "RegionManagerB", contract_b)
    ctx = _ctx(tmp_path, mig, role_a, role_b)
    findings = list(check_rls_role_bindings(ctx))
    assert len(findings) == 2
    assert all(f.severity is Severity.ERROR for f in findings)
    assert all("RegionManager" in f.message for f in findings)
    locators = {f.locator for f in findings}
    assert locators == {role_a, role_b}


def test_not_started_and_blocked_are_not_treated_as_findings_on_their_own(
    tmp_path: Path,
) -> None:
    """A well-formed binding with status not_started (or blocked, with its
    own recorded blocking_reasons) is a lifecycle state HR6 must not
    re-decide or launder into an extra finding -- it only checks structure
    (Principle VIII), never the lifecycle status itself except the
    pass-with-no-evidence defect (FR-008)."""
    mig = _with_fixture_gold(tmp_path)
    not_started = (
        "name: RegionManager\n"
        "filter:\n"
        "  gold_table: gold.dim_store\n"
        "  column: region\n"
        "readiness:\n"
        "  status: not_started\n"
        "  evidence: []\n"
        "  blocking_reasons: []\n"
    )
    role = _role(tmp_path, "sales", "RegionManager", not_started)
    ctx = _ctx(tmp_path, mig, role)
    assert list(check_rls_role_bindings(ctx)) == []

    blocked = (
        "name: OtherManager\n"
        "filter:\n"
        "  gold_table: gold.dim_store\n"
        "  column: region\n"
        "readiness:\n"
        "  status: blocked\n"
        "  evidence: []\n"
        '  blocking_reasons: ["pending owner review"]\n'
    )
    role2 = _role(tmp_path, "other", "OtherManager", blocked)
    ctx2 = _ctx(tmp_path, mig, role, role2)
    assert list(check_rls_role_bindings(ctx2)) == []


# --- static-only, no live-proof claim, no numeric score ---


def test_module_imports_no_database_driver() -> None:
    src = (_REPO / "src" / "seshat" / "rules" / "rls_access.py").read_text(
        encoding="utf-8"
    )
    for forbidden in ("import psycopg", "import sqlalchemy", ".connect(", "DSN"):
        assert forbidden not in src


def test_findings_never_carry_a_numeric_score(tmp_path: Path) -> None:
    mig = _with_fixture_gold(tmp_path)
    not_started_tail = (
        "readiness:\n  status: not_started\n  evidence: []\n  blocking_reasons: []\n"
    )
    defects = [
        (
            'name: A\nfilter:\n  gold_table: gold.dim_store\n  column: ""\n'
            + not_started_tail
        ),
        (
            "name: B\nfilter:\n  gold_table: gold.dim_store\n  column: nope\n"
            + not_started_tail
        ),
        (
            "name: C\nfilter:\n  gold_table: gold.fct_sales\n  column: store_sk\n"
            + not_started_tail
        ),
        (
            "name: D\nfilter:\n  gold_table: gold.dim_store\n  column: region\n"
            "readiness:\n  status: pass\n  evidence: []\n  blocking_reasons: []\n"
        ),
    ]
    rels = [mig]
    for i, text in enumerate(defects):
        rels.append(_role(tmp_path, f"t{i}", f"Role{i}", text))
    ctx = _ctx(tmp_path, *rels)
    findings = list(check_rls_role_bindings(ctx))
    assert findings  # sanity: defects actually triggered
    for f in findings:
        assert "%" not in f.message
        assert not re_has_bare_number_confidence(f.message)


def re_has_bare_number_confidence(message: str) -> bool:
    import re

    return re.search(r"\b\d+\s*(?:/|of)\s*\d+\b", message) is not None


def test_no_c086_specific_token_in_rule_source() -> None:
    src = (_REPO / "src" / "seshat" / "rules" / "rls_access.py").read_text(
        encoding="utf-8"
    )
    for token in ("retail_store_sales", "_rss", "dim_location_rss", "dim_customer_rss"):
        assert token not in src
